# Numpy intro & Practicals #

In [2]:
import numpy as np

In [3]:
np.__version__ # note the use of two underscores.

'1.26.4'

In [4]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

## Create arrays
- An array is a linear data structure where all elements are arranged sequentially. 
- It is a collection of elements of same data type stored at contiguous memory locations.
- Computer programmers use arrays in their programs to organize sets of data in a way that can be easily sorted and searched. 
- They are more efficient at storing data than separate variables and can help a program run faster. 
- In Python, an array is a collection of items stored at contiguous memory locations. 
- The size of an array is determined at the time of declaration. 
- The elements of an array are accessed by their index number. 
- Arrays are mutable, which means that the elements of an array can be changed. 
- Arrays are used to store multiple values in a single variable, instead of declaring separate variables for each value. 
- Arrays are created using the array module. 
- The array module provides a number of functions to perform different operations on arrays. 
- The array module also provides a number of data types to store the elements of an array. 
- The most commonly used data types are: 
- 1. Integers: The array module provides a number of functions to perform different operations on arrays. 
- 2. Floats: The array module provides a number of functions to perform different operations on arrays. 
- 3. Strings: The array module provides a number of functions to perform different operations on arrays. 
- 4. Booleans: The array module provides a number of functions to perform different operations on arrays. 
- 5. Bytes: The array module provides a number of functions to perform different operations on arrays. 
-

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

## Convert list to array

In [7]:
!pip install numpy

'pip' is not recognized as an internal or external command,
operable program or batch file.


In [8]:
arr = np.array(my_list)

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(20,10)

array([], dtype=int32)

In [12]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [13]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [14]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [15]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [16]:
np.zeros(10) # parameter tuning, by default we are getting output in float, system us

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(5, dtype=int) # hyperparameter tuning - here the user changes system parameter

array([0, 0, 0, 0, 0])

In [18]:
np.zeros((2,2), dtype=int) # 2 arrays

array([[0, 0],
       [0, 0]])

In [19]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [20]:
np.zeros((10,15), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [27]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [28]:
rand(3,2)

NameError: name 'rand' is not defined

In [29]:
random.rand(2,3)

NameError: name 'random' is not defined

In [30]:
np.random.rand(2,3) #2 rows 3 columns with float values

array([[0.51785616, 0.36445648, 0.17552981],
       [0.48513189, 0.89128171, 0.05461924]])

In [31]:
np.random.randint(4,6) 
# The output is either 4 or 5 but not 6 because the higher value is excluded
# randint() is an inbuilt function of the random module
# The random module gives access to various useful functions one of them being able to generate random numbers

4

In [33]:
np.random.randint(2,20,4)# output: random 4 digits between 2 to 20 excluding 20

array([ 9, 10,  4,  3])

In [34]:
np.arange(1,13).reshape(3,4) 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
# SLICING IN MATRIX
b=np.random.randint(10,20,(5,4))
b
# ouput: random 5 arrays and 4 columns between 10 and 20, 20 excluded.

array([[13, 15, 15, 13],
       [12, 14, 17, 16],
       [16, 12, 18, 19],
       [15, 12, 17, 19],
       [15, 12, 11, 19]])

In [36]:
## More to come.
n = (5,7)
n1 = (6,8)
print(np.zeros(n)) # parameter tunning
#print(np.zeros(n1,dtype=int)) ## hypyerparameter tunning 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [37]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [39]:
np.ones(4)

array([1., 1., 1., 1.])

In [40]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [41]:
n

(5, 7)

In [42]:
n1

(6, 8)

In [43]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [44]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [45]:
np.ones((2,4)) # 2 rows and 4 columns                                                                              

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.full((2,4), 10) 
# 2 rows and 4 columns
# 10 is the value to fill the matrix

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [47]:
np.full((2,4), 10, dtype = int) # creates a 2x4 array with all elements as 10
# np.ones((2,4), dtype = int) # creates a 2x4 array with all elements as 1
# np.zeros((2,4), dtype = int) # creates a 2x4 array with all elements as 0

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [48]:
np.full((2,4), 100, dtype=int)
# 2 rows and 4 columns

array([[100, 100, 100, 100],
       [100, 100, 100, 100]])

In [49]:
np.arange(10, 50, 5) # 10 to 50 in steps of 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [50]:
np.arange(10, 50, 5, dtype=np.float64) # 10 to 50 in steps of 5 

array([10., 15., 20., 25., 30., 35., 40., 45.])

In [51]:
np.twos((2,4)) # 2D array

AttributeError: module 'numpy' has no attribute 'twos'

In [52]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

## please add new notebook & compare with np & *


In [53]:
np.arange(3)

array([0, 1, 2])

In [54]:
>>> from numpy import *  
# all numpy 217 functions are imported, which is not recommended 
# Because it will take more time to load all the functions
# We can import only the functions we need
# or we can use numpy as np
>>> arange(3)

array([0, 1, 2])

In [55]:
range(12)
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [56]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [57]:
np.threes((3,2))

AttributeError: module 'numpy' has no attribute 'threes'

In [58]:
>>> from numpy import *
>>> zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [60]:
np.random.rand(4)
# array([0.62918006, 0.41324185, 0.09669735, 0.36028141])
# The random.rand function generates a random number between 0 and 1. 

array([0.98257585, 0.18580128, 0.87698735, 0.04813148])

In [61]:
np.random.rand(2)

array([0.05817265, 0.08749236])

In [62]:
np.random.rand(2,4)
# random number between 0 and 1
# 2 rows and 4 columns

array([[0.3527228 , 0.25748613, 0.37794323, 0.86369719],
       [0.93080612, 0.71985672, 0.73761758, 0.7187344 ]])

In [63]:
np.random.rand(3,3)

array([[0.09392617, 0.56017737, 0.70088329],
       [0.76162899, 0.44655167, 0.12517096],
       [0.38361206, 0.77974149, 0.25495067]])

In [64]:
np.random.rand(3,4)

array([[0.67944757, 0.05707399, 0.60301466, 0.55309795],
       [0.64880902, 0.88181141, 0.76001705, 0.16015115],
       [0.79393045, 0.45554389, 0.04831879, 0.21342323]])

In [65]:
np.random.randint(2,20)
# randint is used to generate random integers between 2 and 20
# 1st argument is inclusive and 2nd argument is exclusive

5

In [66]:
np.random.randint(2,20,5) 
# array of 5 random numbers between 2 and 20
# np.random.rand(5) # array of 5 random numbers between 0 and 1



array([13, 14, 14,  5, 19])

In [67]:
np.random.rand(5)

array([0.87757308, 0.48492945, 0.39427528, 0.72294966, 0.16589879])

In [68]:
np.random.randint(5)

2

In [69]:
np.random.randint(0,2)

0

In [70]:
np.random.randint(1,10,4)

array([1, 2, 8, 4])

In [71]:
np.random.randint(1,3,5)

array([2, 2, 2, 2, 1])

In [72]:
np.random.randint(30,20,10) # 10 random numbers between 30 and 20

ValueError: low >= high

In [73]:
np.random.randint(1)

0

In [74]:
np.random.randint(5,9)

7

In [75]:
np.random.randint(10,21,3)  

array([14, 12, 17])

In [76]:
np.random.randint(1,12,10)

array([11,  3,  1, 11,  4,  8,  7,  3,  3,  5])

In [77]:
np.random.randint(10,40,(10,10)) 
# generate random numbers between 10 and 30 with 10 rows and 10 columns
# np.random.randint(10,40,(10,10))

array([[34, 27, 22, 29, 20, 31, 21, 15, 15, 20],
       [36, 11, 36, 24, 36, 15, 29, 27, 25, 11],
       [29, 36, 33, 13, 32, 28, 33, 36, 15, 30],
       [14, 33, 25, 10, 37, 14, 11, 14, 12, 28],
       [17, 34, 23, 29, 20, 14, 24, 38, 29, 34],
       [24, 19, 10, 21, 12, 26, 26, 13, 12, 26],
       [18, 33, 28, 25, 34, 39, 37, 28, 39, 11],
       [12, 39, 14, 34, 32, 31, 18, 26, 25, 29],
       [27, 10, 29, 19, 31, 10, 13, 24, 24, 34],
       [39, 37, 36, 25, 27, 21, 30, 38, 12, 26]])

In [78]:
b = np.random.randint(10,20,(5,4))
b
# Generate random number between 10 and 20 with 5 rows and 4 columns

array([[14, 18, 14, 16],
       [17, 13, 18, 15],
       [14, 12, 12, 17],
       [18, 12, 13, 14],
       [19, 14, 16, 14]])

In [79]:
b[:] # slicing

array([[14, 18, 14, 16],
       [17, 13, 18, 15],
       [14, 12, 12, 17],
       [18, 12, 13, 14],
       [19, 14, 16, 14]])

In [80]:
b[0:2] # first two elements

array([[14, 18, 14, 16],
       [17, 13, 18, 15]])

In [81]:
b

array([[14, 18, 14, 16],
       [17, 13, 18, 15],
       [14, 12, 12, 17],
       [18, 12, 13, 14],
       [19, 14, 16, 14]])

In [82]:
b[0:-1] # slice from first to second last element

array([[14, 18, 14, 16],
       [17, 13, 18, 15],
       [14, 12, 12, 17],
       [18, 12, 13, 14]])

In [83]:
b[-1] # last element/row

array([19, 14, 16, 14])

In [84]:
b[-1:] # last element

array([[19, 14, 16, 14]])

In [85]:
b[-1, :] # last row

array([19, 14, 16, 14])

In [86]:
b[:, -1] # last column

array([16, 15, 17, 14, 14])

In [87]:
b[:, :-1] # all rows, except last column

array([[14, 18, 14],
       [17, 13, 18],
       [14, 12, 12],
       [18, 12, 13],
       [19, 14, 16]])

In [88]:
b[:, -2:] # last two columns

array([[14, 16],
       [18, 15],
       [12, 17],
       [13, 14],
       [16, 14]])

In [89]:
b[-1, -2:] # last row, last two columns

array([16, 14])

In [90]:
b[-1, -2:-1] # last row, last two columns

array([16])

In [91]:
b[-1, -2:-1:1] # last row, last two columns

array([16])

In [92]:
b[-1, -2:-1:2] # slice last row from second last to second element in each row

array([16])

In [93]:
b

array([[14, 18, 14, 16],
       [17, 13, 18, 15],
       [14, 12, 12, 17],
       [18, 12, 13, 14],
       [19, 14, 16, 14]])

In [94]:
b[0,2]

14

In [95]:
b[1,3] # 

15

In [96]:
b[1,1]

13

In [97]:
b[4,3]

14

In [98]:
b[2,2]

12

In [99]:
b[4,5]

IndexError: index 5 is out of bounds for axis 1 with size 4

In [100]:
b[3,4]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [101]:
  b[1:3] # slicing. print the raws 1 to 3. will print only 2 and 3rd raws (specifically)

array([[17, 13, 18, 15],
       [14, 12, 12, 17]])

In [102]:
b[1,2] # from the first raw, print second column

18

In [103]:
b[1,-1] 

15

In [104]:
b[2:3] # semicolon is slicing

array([[14, 12, 12, 17]])

In [105]:
 b[0:-2]

array([[14, 18, 14, 16],
       [17, 13, 18, 15],
       [14, 12, 12, 17]])

In [106]:
b[0,2] # comma gives coordinates

14

In [107]:
 b[-5,-3]

18

In [108]:
b[-4,2]

18

## Operations

Note: there are 2 special concepts in Python: __name__ and __init__

In [109]:
__name__

'__main__'

In [110]:
a = np.random.randint(10,20,5) # generating random array of 5 elements from 10 to 20
a

array([11, 18, 11, 10, 17])

In [111]:
arr

array([0, 1, 2, 3, 4, 5])

In [112]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[13, 64, 79, 65,  1, 73,  1, 46, 53, 55],
       [83, 16, 28, 10, 46, 55, 92, 57, 14, 55],
       [ 6, 91, 71, 82, 27, 27, 94, 12, 14, 18],
       [83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [43,  0, 69, 11, 79, 91, 56, 65, 35, 83],
       [72, 94, 52, 21, 63, 76, 70, 72, 62, 88],
       [33, 81, 67, 89, 36, 35, 98, 37, 47, 21],
       [75, 24, 10, 25, 91, 53, 42, 80, 19, 21],
       [45, 84, 69, 90, 80, 80, 48, 96, 78, 27],
       [94, 39,  3, 61, 94, 63, 53, 83, 43, 65]])

In [113]:
arr

array([0, 1, 2, 3, 4, 5])

In [115]:
arr[:] # all elements
# arr[1:3] # 1st and 2nd elements
# arr[1:3] = 100 # replace 1st and 2nd elements with 100
# arr[1:3] = [1, 2] # replace 1st and 2nd elements with 1 and 2 respectively
# arr[1:3] = [1, 2, 3] # replace 1st and 2nd elements with 1, 2 and 3 respectively
# arr[1:3] = [1, 2, 3, 4] # replace 1st and 2nd elements with 1, 2, 3 and 4 respectively
# arr[1:3] = [1, 2, 3, 4, 5, 6] # replace 1st and 2nd elements with 1, 2, 3, 4, 5 and 6 respectively
# arr[1:3] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # replace 1st and 2nd elements with 1, 2, 3, 4, 5, 6, 7, 8, 9 

array([0, 1, 2, 3, 4, 5])

In [116]:
arr[:4] # 

array([0, 1, 2, 3])

In [117]:
arr2[:]

array([[13, 64, 79, 65,  1, 73,  1, 46, 53, 55],
       [83, 16, 28, 10, 46, 55, 92, 57, 14, 55],
       [ 6, 91, 71, 82, 27, 27, 94, 12, 14, 18],
       [83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [43,  0, 69, 11, 79, 91, 56, 65, 35, 83],
       [72, 94, 52, 21, 63, 76, 70, 72, 62, 88],
       [33, 81, 67, 89, 36, 35, 98, 37, 47, 21],
       [75, 24, 10, 25, 91, 53, 42, 80, 19, 21],
       [45, 84, 69, 90, 80, 80, 48, 96, 78, 27],
       [94, 39,  3, 61, 94, 63, 53, 83, 43, 65]])

In [122]:
arr2[0:5] # 
# Slicing of 1D array
# 


array([[13, 64, 79, 65,  1, 73,  1, 46, 53, 55],
       [83, 16, 28, 10, 46, 55, 92, 57, 14, 55],
       [ 6, 91, 71, 82, 27, 27, 94, 12, 14, 18],
       [83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [43,  0, 69, 11, 79, 91, 56, 65, 35, 83]])

In [120]:
arr2

array([[13, 64, 79, 65,  1, 73,  1, 46, 53, 55],
       [83, 16, 28, 10, 46, 55, 92, 57, 14, 55],
       [ 6, 91, 71, 82, 27, 27, 94, 12, 14, 18],
       [83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [43,  0, 69, 11, 79, 91, 56, 65, 35, 83],
       [72, 94, 52, 21, 63, 76, 70, 72, 62, 88],
       [33, 81, 67, 89, 36, 35, 98, 37, 47, 21],
       [75, 24, 10, 25, 91, 53, 42, 80, 19, 21],
       [45, 84, 69, 90, 80, 80, 48, 96, 78, 27],
       [94, 39,  3, 61, 94, 63, 53, 83, 43, 65]])

In [121]:
arr2[1,5] # returns the element at 2nd row and 5th column

55

In [123]:
arr2

array([[13, 64, 79, 65,  1, 73,  1, 46, 53, 55],
       [83, 16, 28, 10, 46, 55, 92, 57, 14, 55],
       [ 6, 91, 71, 82, 27, 27, 94, 12, 14, 18],
       [83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [43,  0, 69, 11, 79, 91, 56, 65, 35, 83],
       [72, 94, 52, 21, 63, 76, 70, 72, 62, 88],
       [33, 81, 67, 89, 36, 35, 98, 37, 47, 21],
       [75, 24, 10, 25, 91, 53, 42, 80, 19, 21],
       [45, 84, 69, 90, 80, 80, 48, 96, 78, 27],
       [94, 39,  3, 61, 94, 63, 53, 83, 43, 65]])

In [125]:
arr2[-5,5] # returns the 5th element of the 5th row

76

In [126]:
arr2[-5,-5] # 

76

In [127]:
arr2[-1,-2]

43

In [130]:
arr2[::-1] # reverse the array

array([[94, 39,  3, 61, 94, 63, 53, 83, 43, 65],
       [45, 84, 69, 90, 80, 80, 48, 96, 78, 27],
       [75, 24, 10, 25, 91, 53, 42, 80, 19, 21],
       [33, 81, 67, 89, 36, 35, 98, 37, 47, 21],
       [72, 94, 52, 21, 63, 76, 70, 72, 62, 88],
       [43,  0, 69, 11, 79, 91, 56, 65, 35, 83],
       [83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [ 6, 91, 71, 82, 27, 27, 94, 12, 14, 18],
       [83, 16, 28, 10, 46, 55, 92, 57, 14, 55],
       [13, 64, 79, 65,  1, 73,  1, 46, 53, 55]])

In [ ]:
arr2[::-2] # reverse every second element

array([[94, 39,  3, 61, 94, 63, 53, 83, 43, 65],
       [75, 24, 10, 25, 91, 53, 42, 80, 19, 21],
       [72, 94, 52, 21, 63, 76, 70, 72, 62, 88],
       [83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [83, 16, 28, 10, 46, 55, 92, 57, 14, 55]])

In [131]:
arr2[::-3] # reverse of every third element
# arr2[::3] # every third element

array([[94, 39,  3, 61, 94, 63, 53, 83, 43, 65],
       [33, 81, 67, 89, 36, 35, 98, 37, 47, 21],
       [83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [13, 64, 79, 65,  1, 73,  1, 46, 53, 55]])

In [133]:
arr2[::3] # skip every 3rd element

array([[13, 64, 79, 65,  1, 73,  1, 46, 53, 55],
       [83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [33, 81, 67, 89, 36, 35, 98, 37, 47, 21],
       [94, 39,  3, 61, 94, 63, 53, 83, 43, 65]])

In [ ]:
arr2[:-3] # this will give you all the elements except the last 3 elements


array([[13, 64, 79, 65,  1, 73,  1, 46, 53, 55],
       [83, 16, 28, 10, 46, 55, 92, 57, 14, 55],
       [ 6, 91, 71, 82, 27, 27, 94, 12, 14, 18],
       [83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [43,  0, 69, 11, 79, 91, 56, 65, 35, 83],
       [72, 94, 52, 21, 63, 76, 70, 72, 62, 88],
       [33, 81, 67, 89, 36, 35, 98, 37, 47, 21]])

In [135]:
arr2[-3:] # this will give you the last 3 elements

array([[75, 24, 10, 25, 91, 53, 42, 80, 19, 21],
       [45, 84, 69, 90, 80, 80, 48, 96, 78, 27],
       [94, 39,  3, 61, 94, 63, 53, 83, 43, 65]])

In [136]:
arr2[3:] # returns the array from index 3 to the end
# arr2[:3] # returns the array from the start to index 3
# arr2[1:4] # returns the array from index 1 to index 4
# arr2[1:-1] # returns the array from index 1 to the second last element
# arr2[:1] # returns the array from the start to index 1
# arr2[-1:] # returns the array from the last element to the last element
# arr2[:-1] # returns the array from the start to the second last element
# arr2[1:] # returns the array from index 1 to the end

array([[83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [43,  0, 69, 11, 79, 91, 56, 65, 35, 83],
       [72, 94, 52, 21, 63, 76, 70, 72, 62, 88],
       [33, 81, 67, 89, 36, 35, 98, 37, 47, 21],
       [75, 24, 10, 25, 91, 53, 42, 80, 19, 21],
       [45, 84, 69, 90, 80, 80, 48, 96, 78, 27],
       [94, 39,  3, 61, 94, 63, 53, 83, 43, 65]])

In [137]:
arr2

array([[13, 64, 79, 65,  1, 73,  1, 46, 53, 55],
       [83, 16, 28, 10, 46, 55, 92, 57, 14, 55],
       [ 6, 91, 71, 82, 27, 27, 94, 12, 14, 18],
       [83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [43,  0, 69, 11, 79, 91, 56, 65, 35, 83],
       [72, 94, 52, 21, 63, 76, 70, 72, 62, 88],
       [33, 81, 67, 89, 36, 35, 98, 37, 47, 21],
       [75, 24, 10, 25, 91, 53, 42, 80, 19, 21],
       [45, 84, 69, 90, 80, 80, 48, 96, 78, 27],
       [94, 39,  3, 61, 94, 63, 53, 83, 43, 65]])

In [ ]:
arr2[0:10:3] 
# this is a slice of the array
# 

array([[13, 64, 79, 65,  1, 73,  1, 46, 53, 55],
       [83, 78, 49, 63, 21, 47, 73, 10, 63, 19],
       [33, 81, 67, 89, 36, 35, 98, 37, 47, 21],
       [94, 39,  3, 61, 94, 63, 53, 83, 43, 65]])

In [140]:
arr

array([0, 1, 2, 3, 4, 5])

In [139]:
arr.max()

5

In [141]:
arr.min()

0

In [142]:
arr.mean()

2.5

In [ ]:
arr.median() # median of the array
# arr.std() # standard deviation of the array
# arr.var() # variance of the array

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [144]:
>>> from numpy import *
>>> a = array([1,2,3,4,9])
>>> median(a)

3.0

In [145]:
arr.std()

1.707825127659933

In [146]:
arr.var()

2.9166666666666665

In [147]:
arr

array([0, 1, 2, 3, 4, 5])

In [153]:
print(arr.reshape(2,3)) # 2 rows and 3 columns
print(arr.reshape(3,2)) # 3 rows and 2 columns

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [154]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [155]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [156]:
arr.reshape(1,5)

ValueError: cannot reshape array of size 6 into shape (1,5)

In [ ]:
arr.reshape(3,2,order='C') # C is the default order


array([[0, 1],
       [2, 3],
       [4, 5]])

In [159]:
arr.reshape(3,2,order='F') # F - Fortran order
# Fortran order means that the elements are stored in the order in which they appear in the array
# C order means that the elements are stored in the order in which they appear in the memory
# C order is the default order in numpy 

array([[0, 3],
       [1, 4],
       [2, 5]])

In [161]:
arr.reshape(3,2,order='A')
# order='A' is used to change the order of the elements in the array


array([[0, 1],
       [2, 3],
       [4, 5]])

In [162]:
arr.reshape(3,2,order='K') # K = C-contiguous
# arr.reshape(3,2,order='A') # A = F-contiguous

ValueError: order 'K' is not permitted for reshaping

In [163]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [164]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [165]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [166]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

## Indexing

In [167]:
mat = np.arange(0,100).reshape(10,10)

In [168]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [170]:
row = 4 # number of rows
col = 5 # number of columns


In [171]:
col

5

In [172]:
row

4

In [173]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [175]:
mat[row,col]

45

In [176]:
mat[4,5]

45

In [177]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [178]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
col = 6

In [180]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# With Slices
mat[:,col] # selects all rows and all columns except col
# mat[:,col+1:] # selects all rows and all columns except col and the last one
# mat[:,col:-1] # selects all rows and all columns except col and the last one

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [182]:
mat[:,col+1:]

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29],
       [37, 38, 39],
       [47, 48, 49],
       [57, 58, 59],
       [67, 68, 69],
       [77, 78, 79],
       [87, 88, 89],
       [97, 98, 99]])

In [184]:
mat[:,col:-1]

array([[ 6,  7,  8],
       [16, 17, 18],
       [26, 27, 28],
       [36, 37, 38],
       [46, 47, 48],
       [56, 57, 58],
       [66, 67, 68],
       [76, 77, 78],
       [86, 87, 88],
       [96, 97, 98]])

In [185]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [187]:
mat[row,:]
# row slicing: mat[row,:]
# column slicing: mat[:,col]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [188]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [ ]:
mat[:col]
# :col means all rows
# 1:3 means 1 and 2 rows in mat[1:3, 1:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [190]:
row

4

In [191]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [192]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [193]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [196]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
mat[:,8] # 8th column
# mat[:,8:10] # 8th and 9th column
# mat[1:3,1:3] # 2nd and 3rd row and 2nd and 3rd column


array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [198]:
mat[:,8:10] # 8th and 9th column

array([[ 8,  9],
       [18, 19],
       [28, 29],
       [38, 39],
       [48, 49],
       [58, 59],
       [68, 69],
       [78, 79],
       [88, 89],
       [98, 99]])

In [200]:
mat[1:3,1:3]

array([[11, 12],
       [21, 22]])

In [201]:
mat[:,-1] # last column
# mat[:,1:] # all rows, 1st column onwards
# mat[:,[1,2]] # all rows, 2nd and 3rd column

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [202]:
mat[:,1:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49],
       [51, 52, 53, 54, 55, 56, 57, 58, 59],
       [61, 62, 63, 64, 65, 66, 67, 68, 69],
       [71, 72, 73, 74, 75, 76, 77, 78, 79],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [203]:
mat[:,[1,2]]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [204]:
row

4

In [205]:
col

6

In [206]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [207]:
mat[1,4]

14

In [208]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [209]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [210]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [211]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [212]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [213]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [215]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [216]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [217]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [218]:
mat[4]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [219]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [220]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [222]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [223]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [224]:
mat[::-4]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [225]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [226]:
mat[::-6]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [227]:
mat[::-1,::-1]

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])

In [228]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [229]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
mat[2:6,2:4] 
# 2:4 is the row and column
# 1:5 --> only row part /// 1:3 -- it indicates only column parts
# 1:5,1:3 -- it indicates both row and column 


array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [232]:
mat[1:5,1:3]

array([[11, 12],
       [21, 22],
       [31, 32],
       [41, 42]])

In [233]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [234]:
mat[1,6]

16

In [235]:
mat[0,1]

1

In [236]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [237]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [238]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
mat[:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [240]:
mat[:1] == mat[0:1]

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [241]:
mat[3,5]

35

In [242]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [246]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [249]:
mat[1:2] # row slicing

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [250]:
mat[2:4] # row slicing from 2 to 4

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [251]:
mat[1:2,2:4] 
# This means that the first index is inclusive and the second is exclusive.
# This is the same as the slice operator in Python.

array([[12, 13]])

In [252]:
mat[2:3]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [253]:
mat[2:3,2:3] 


array([[22]])

In [254]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [256]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [259]:
mat[2:4,]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [255]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

In [260]:
mat[2:3,4:5]

array([[24]])

## Masking, called also filtering 
- It is a way of selecting a subset of the elements of an array.
- Masking is done by creating a boolean array of the same shape as the array we want to mask, and then using this boolean array to select the elements of the original array that we want to keep.

In [261]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [263]:
id(mat)

2249429100720

In [264]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [265]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [266]:
mat<=50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
mat>=50
# The output provides conditions False or True but not values
# Use mat[mat>50] to get values 

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [270]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [271]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [272]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [273]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [275]:
mat[mat>0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [276]:
mat[mat>=70]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [278]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [279]:
mat[mat==50]

array([50])

Next steps:
- How to generate OTP
- Next session, start visualisation/images
- How images break down into matrices